theme = "solarized-dark"
icons = "awesome"
interval = 1
font = "Vazir 16"

[[block]]
block = "pacman"
interval = 600
format = "{pacman} updates available"
format_singular = "{pacman} update available."
format_up_to_date = "System is up to date."
critical_updates_regex = "(linux|linux-lts|linux-zen)"
on_click = "pamac-manager"
[block.theme_overrides]
idle_bg = "#ff8e1d"
idle_fg = "#ffffff"

[[block]]
block = "custom"
# command = "echo '   ' && curl https://api.ipify.org"
cycle = ["cmd=$(curl https://api.ipify.org) && icon='     ' && result=$icon$cmd && echo $result", "cmd=`ip route get 8.8.8.8 | head -1 | awk '{print $7}'` && icon='     ' && result=$icon$cmd && echo $result"]
interval = 5
[block.theme_overrides]
idle_bg = "#00aa7f"
idle_fg = "#ffffff"

[[block]]
block = "net"
format = "{signal_strength} {ssid}"
icons_format = " {icon} "
[block.theme_overrides]
idle_bg = "#050c8a"
idle_fg = "#ffffff"

#[[block]]
#block = "bluetooth"
#mac = "4c:0f:6e:fb:71:8f"
#format = "{signal_strength} {ssid}"
#hide_disconnected = true
#[block.theme_overrides]
#idle_bg = "#954eff"
#idle_fg = "#ffffff"

#[[block]]
#block = "disk_space"
#path = "/"
#alias = "/"
#info_type = "available"
#unit = "GB"
#interval = 20
#warning = 20.0
#alert = 10.0
#format = "  Root: {available}"
#[block.theme_overrides]
#idle_bg = "#ff0b40"
#idle_fg = "#ffffff"

#[[block]]
#block = "disk_space"
#path = "/home/hadi/"
#alias = "/home/hadi/"
#info_type = "available"
#unit = "GB"
#interval = 20
#warning = 20.0
#alert = 10.0
#format = "  Home: {available}"
#[block.theme_overrides]
#idle_bg = "#4b9f9f"
#idle_fg = "#ffffff"

[[block]]
block = "custom"
cycle = ["cmd=$(df -h / | tail -1 | awk '{print $4}') && icon='‌  ‌ ‌‌      Root: ' && result=$icon$cmd && echo $result", "cmd=$(df -h /home/hadi | tail -1 | awk '{print $4}') && icon='   ‌ ‌ ‌   Home: ' && result=$icon$cmd && echo $result"]
[block.theme_overrides]
idle_bg = "#ff0b40"
idle_fg = "#ffffff"

[[block]]
interval = 1
block = "memory"
display_type = "memory"
format_mem = "{mem_used} / {mem_total} "
format_swap = " {swap_used} / {swap_total}"
icons_format = "  {icon}"
[block.theme_overrides]
idle_bg = "#889f13"
idle_fg = "#ffffff"

[[block]]
block = "cpu"
interval = 1
format = "  {utilization} {barchart}"
icons_format = ""
[block.theme_overrides]
idle_bg = "#435388"
idle_fg = "#ffffff"


[[block]]
block = "load"
interval = 1
format = "{1m}"
icons_format = "  {icon} "
[block.theme_overrides]
idle_bg = "#3b7979"
idle_fg = "#ffffff"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "min: {min} / max: {max} / avg: {average}"
chip = "*-isa-*"
[block.theme_overrides]
idle_fg = "#ffffff"

[[block]]
block = "backlight"
icons_format = "    {icon} "
[block.theme_overrides]
idle_bg = "#ac3070"
idle_fg = "#ffffff"

[[block]]
block = "sound"
format = "     {volume}"
icons_format = ""
[block.theme_overrides]
idle_bg = "#88624c"
idle_fg = "#ffffff"

[[block]]
block = "custom"
command = "cmd=$(xkb-switch -p) && icon='‌‌‌‌‌  ‌ ‌ ‌       ‌ ' && result=$icon$cmd && echo $result"
on_click = "xkb-switch -n"
interval = 0.5
[block.theme_overrides]
idle_bg = "#00cbde"
idle_fg = "#ffffff"

[[block]]
block = "battery"
interval = 10
format = "  {percentage}"
icons_format = "  {icon}"
[block.theme_overrides]
idle_fg = "#ffffff"

[[block]]
block = "time"
interval = 60
format = "     %a %d/%m %R"
icons_format = ""
[block.theme_overrides]
idle_bg = "#2d7083"
idle_fg = "#ffffff"

[[block]]
block = "custom"
command = "echo '    '"
on_click = "i3-nagbar -t warning -m 'Do you really want to exit i3? This will end your X session.' -B 'Yes, Log Out!' 'i3-msg exit'"
interval = "once"
[block.theme_overrides]
idle_bg = "#0d0562"
idle_fg = "#ffffff"

[[block]]
block = "custom"
command = "echo "
on_click = "i3-nagbar -t warning -m 'Do you really want to reboot your ?' -B 'Yes, Reboot!' 'reboot'"
interval = "once"
[block.theme_overrides]
idle_bg = "#0d0562"
idle_fg = "#ffffff"

[[block]]
block = "custom"
command = "echo "
on_click = "i3-nagbar -t warning -m 'Do you really want to shutdown?' -B 'Yes, Shutdown!' 'shutdown now'"
interval = "once"
[block.theme_overrides]
idle_bg = "#0d0562"
idle_fg = "#ffffff"

